### ISSUE TITLE
Which version of JsonCpp?

### ISSUE THREAD

**Issue by smallfly** [bakercp/ofxSQLiteCpp#4]
Hi,

Do you use any specific version of JsonCpp with this add-on?
Are you using [ofxJSON](https://github.com/bakercp/ofxJSON/blob/master/libs/jsoncpp/include/json/json.h) or [JsonCpp](https://github.com/open-source-parsers/jsoncpp) directly?

Thanks,

Hugues.

**Comment by smallfly** [comment]
To add to my previous message:

I just realized that OF core now includes a JSON lib. Should ofxSQLiteCpp be using this JSON lib instead of JsonCpp?

**Comment by bakercp** [comment]
Yes, core Json should be used for 0.10.0 going forward.  For previous versions I used ofxJSON.

**Comment by smallfly** [comment]
This has been clearly answered. I don't think it needs to stay open.
