### ISSUE TITLE
write example not work ofx010

### ISSUE THREAD

**Issue by Wolftronics-SBC** [bakercp/ofxSQLiteCpp#9]
hi!
write example not work?
thanks.

**Comment by bakercp** [comment]
It doesn't work?

**Comment by Wolftronics-SBC** [comment]
sql file to change something. but there are no sql data.

**Comment by bakercp** [comment]
Can you please be very specific. I don't know what platform you're using, what version of openFrameworks, what version of this addon, what the exact steps are to reproduce the issue, what the errors are etc.  I am unable to find any addon called `ofx010`. https://github.com/search?utf8=%E2%9C%93&q=ofx010&type=

**Comment by Wolftronics-SBC** [comment]
openframeworks master repo and ubuntu 16.04.3
You work for you insert example?

**Comment by Wolftronics-SBC** [comment]
inserting ending drop table :) working
